// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto

package com.poc.api.grpc.v1;

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poc_v1_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poc_v1_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poc_v1_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poc_v1_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rExample.proto\022\ncom.poc.v1\"\034\n\014HelloRequ" +
      "est\022\014\n\004name\030\001 \001(\t\"\032\n\nHelloReply\022\014\n\004text\030" +
      "\001 \001(\t2K\n\tMyService\022>\n\010SayHello\022\030.com.poc" +
      ".v1.HelloRequest\032\026.com.poc.v1.HelloReply" +
      "\"\000B\027\n\023com.poc.api.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_poc_v1_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poc_v1_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poc_v1_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_poc_v1_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_poc_v1_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poc_v1_HelloReply_descriptor,
        new java.lang.String[] { "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
