// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Example.proto

package com.poc.api.grpc.v1;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.poc.v1.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
